// Store branding utilities for documents
export interface StoreData {
  id: string;
  name: string;
  description?: string;
  address: string;
  phone: string;
  email: string;
  logoUrl?: string;
  primaryColor: string;
}

/**
 * Generate CSV with store branding header
 */
export function generateBrandedCSV(
  store: StoreData,
  data: Record<string, unknown>[],
  headers: string[],
  title: string
): string {
  const lines: string[] = [];
  
  // Add store header
  lines.push(`${store.name}`);
  lines.push(`${store.address}`);
  lines.push(`Phone: ${store.phone} | Email: ${store.email}`);
  lines.push(''); // Empty line
  lines.push(title);
  lines.push(`Generated on: ${new Date().toLocaleString()}`);
  lines.push(''); // Empty line
  
  // Add table headers
  lines.push(headers.join(','));
  
  // Add data rows
  data.forEach(row => {
    const values = headers.map(header => {
      const value = row[header] || '';
      // Escape commas and quotes in CSV
      return typeof value === 'string' && (value.includes(',') || value.includes('"'))
        ? `"${value.replace(/"/g, '""')}"`
        : value;
    });
    lines.push(values.join(','));
  });
  
  return lines.join('\n');
}

/**
 * Generate HTML for PDF with store branding
 */
export function generateBrandedHTML(
  store: StoreData,
  content: string,
  title: string
): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title} - ${store.name}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      border-bottom: 3px solid ${store.primaryColor};
      padding-bottom: 20px;
      margin-bottom: 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }
    .logo-section {
      display: flex;
      align-items: center;
      gap: 15px;
    }
    .logo {
      width: 60px;
      height: 60px;
      border-radius: 8px;
      object-fit: cover;
    }
    .logo-placeholder {
      width: 60px;
      height: 60px;
      border-radius: 8px;
      background-color: ${store.primaryColor};
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-size: 24px;
      font-weight: bold;
    }
    .store-info h1 {
      margin: 0;
      font-size: 28px;
      color: ${store.primaryColor};
    }
    .store-info p {
      margin: 5px 0 0 0;
      color: #666;
      font-size: 14px;
    }
    .document-info {
      text-align: right;
      color: #666;
      font-size: 14px;
    }
    .content {
      margin-top: 30px;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #eee;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #eee;
    }
    th {
      background-color: ${store.primaryColor}20;
      color: ${store.primaryColor};
      font-weight: 600;
    }
    tr:hover {
      background-color: #f9f9f9;
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo-section">
      ${store.logoUrl 
        ? `<img src="${store.logoUrl}" alt="${store.name}" class="logo" />`
        : `<div class="logo-placeholder">${store.name.charAt(0)}</div>`
      }
      <div class="store-info">
        <h1>${store.name}</h1>
        <p>${store.address}</p>
        <p>📞 ${store.phone} | ✉️ ${store.email}</p>
      </div>
    </div>
    <div class="document-info">
      <p><strong>${title}</strong></p>
      <p>Generated: ${new Date().toLocaleString()}</p>
    </div>
  </div>
  
  <div class="content">
    ${content}
  </div>
  
  <div class="footer">
    <p>Generated by ${store.name} - Powered by SwiftStock</p>
  </div>
</body>
</html>
  `;
}

/**
 * Download file with branded filename
 */
export function downloadBrandedFile(
  store: StoreData,
  content: string,
  type: 'csv' | 'html',
  reportName: string
) {
  const timestamp = new Date().toISOString().slice(0, 10);
  const storeName = store.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const filename = `${storeName}-${reportName}-${timestamp}.${type}`;
  
  const mimeType = type === 'csv' ? 'text/csv' : 'text/html';
  const blob = new Blob([content], { type: mimeType });
  const url = window.URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}

/**
 * Get store brand styles for components
 */
export function getStoreBrandStyles(store: StoreData | null) {
  const primaryColor = store?.primaryColor || '#3B82F6';
  
  return {
    primaryColor,
    buttonStyle: {
      backgroundColor: primaryColor,
      borderColor: primaryColor,
    },
    linkStyle: {
      color: primaryColor,
    },
    headerStyle: {
      borderBottomColor: primaryColor,
    },
    badgeStyle: {
      backgroundColor: `${primaryColor}20`,
      color: primaryColor,
    }
  };
}